import assert from 'node:assert/strict';
import {averageBuy,purchaseAverages} from './average-buy.ts';
import {remainingBasis} from './core.ts';
import type {Fact,Acquisitions} from './core.ts';
assert.equal(averageBuy(20*1.05,1),21);
assert.equal(averageBuy(42,2),21);
assert.equal(averageBuy(0,1),0);
assert.equal(averageBuy(null,1),null);
assert.equal(averageBuy(20,null),null);
assert.equal(averageBuy(20,0),null);
const time=Date.parse('2022-05-31T12:00:00Z')/1000;
const buy:Fact={hash:'purchase',time,adaRaw:'0',feeRaw:null,assets:{nft:'1'},decimals:{nft:0},internal:false,wallets:[],swapCandidate:true};
const send={...buy,hash:'send',time:time+1,assets:{nft:'-1'}};
const receive={...buy,hash:'receive',time:time+2};
const acquisitions:Acquisitions={purchase:{nft:{raw:'1',ada:1000,time,paymentHash:'purchase',source:'marketplace'}}};
const history={'2022-05-31':0.63033,'2022-06-01':1};
const facts=[buy,send,receive,buy];
assert.equal(remainingBasis(facts,history,acquisitions).nft.usd,null,'unverified return retains unknown remaining cost');
const purchased=purchaseAverages(facts,history,acquisitions).nft;
assert.equal(purchased.count,1,'duplicate facts and unpriced returns do not add purchases');
assert.ok(Math.abs(averageBuy(purchased.usd,Number(purchased.raw))!-630.33)<1e-9);
const second={...buy,hash:'second',time:time+86400,assets:{nft:'2'}};
const all={...acquisitions,second:{nft:{raw:'2',ada:300,time:second.time,paymentHash:'second',source:'confirmed' as const}}};
const combined=purchaseAverages([...facts,second],history,all).nft;
assert.equal(combined.raw,3n);
assert.ok(Math.abs(averageBuy(combined.usd,Number(combined.raw))!-310.11)<1e-9,'quantity-weighted purchases use their own dated rates');
assert.equal(purchaseAverages([...facts,second],{'2022-05-31':0.63033},all).nft.usd,null);
assert.deepEqual(purchaseAverages([{...buy,internal:true}],history,acquisitions),{});
console.log('Average buy displays known USD costs, including zero, independently from current price');
