import assert from 'node:assert/strict';
import {base58} from '@scure/base';
import {encode,Tagged} from 'cborg';
import CRC32 from 'crc-32';
import {analyse} from './core.ts';
import {cexAdaNetPosition,normalizeCexAddresses} from './cex.ts';
import {discoveredByronAddresses,saveByronSelection,byronAddressTransactions} from './byron-exchanges.ts';
function address(seed:number){
  const payload=encode([new Uint8Array(28).fill(seed),new Map(),0]);
  return base58.encode(encode([new Tagged(24,payload),CRC32.buf(payload)>>>0]));
}
const a=address(1),b=address(2),own=address(3),saved=address(4);
const io=(address:string,value:string)=>({payment_addr:{bech32:address},value,asset_list:[]});
const buy=analyse({tx_hash:'buy',tx_timestamp:1,fee:'200000',inputs:[io(a,'5000000'),io(b,'5200000')],outputs:[io(own,'10000000')]},new Set([own]));
const sell=analyse({tx_hash:'sell',tx_timestamp:2,fee:'200000',inputs:[io(own,'10000000')],outputs:[io(a,'4000000'),io(b,'5800000')]},new Set([own]));
const existing=[{address:saved,name:'Saved CEX'}];
const verification=byronAddressTransactions([buy,buy,sell],a);
assert.equal(verification.length,2);
assert.equal(verification[0].amountRaw,'4000000');
assert.equal(verification[0].side,'sell');
assert.equal(verification[1].amountRaw,null);
assert.equal(verification[1].walletChangeRaw,'10000000');
assert.deepEqual(byronAddressTransactions([buy,sell],saved),[]);
const found=discoveredByronAddresses([buy,buy,sell],[own],existing);
assert.equal(found.length,3);
assert.deepEqual(found.find(row=>row.address===a),{address:a,transactions:2,lastSeen:2});
assert.deepEqual(found.find(row=>row.address===saved),{address:saved,transactions:0,lastSeen:null});
assert.equal(discoveredByronAddresses([buy],[a,b],[]).length,0);
const newest=analyse({tx_hash:'newest',tx_timestamp:100,fee:'200000',inputs:[io(own,'10000000')],outputs:[io(saved,'9800000')]},new Set([own]));
const noHistory=address(5);
const chronological=discoveredByronAddresses([sell,newest,buy],[own],[...existing,{address:noHistory,name:'No history'}]);
assert.equal(chronological[0].address,saved,'newest transaction wins over a higher transaction count');
assert.equal(chronological.at(-1)?.address,noHistory,'missing dates appear last');
assert.deepEqual(chronological.slice(1,3).map(row=>row.address),[a,b].sort((x,y)=>x.localeCompare(y)),'ties have stable address order');
assert.deepEqual(byronAddressTransactions([buy,newest,sell],saved).map(row=>row.time),[100]);
assert.deepEqual(byronAddressTransactions([buy,sell],a).map(row=>row.time),[2,1]);
const unrelated={address:'stake1existing',name:'Existing'};
const selected=saveByronSelection([...existing,unrelated],[a,b,saved,own,'invalid'],new Set([a,b,own,'invalid']),'Exchange',[own]);
assert.deepEqual(selected,[unrelated,{address:a,name:'Exchange'},{address:b,name:'Exchange'}]);
const group=selected.filter(row=>row.address!==unrelated.address);
assert.deepEqual(normalizeCexAddresses(JSON.parse(JSON.stringify(group))),group);
assert.deepEqual(cexAdaNetPosition([buy,buy,sell,sell],group,'0'),{receivedRaw:'10000000',sentRaw:'9800000',netRaw:'-200000'});
assert.deepEqual(cexAdaNetPosition([buy,sell],[],'0'),{receivedRaw:'0',sentRaw:'0',netRaw:'0'});
const shared=byronAddressTransactions([buy,buy,sell],a,group);
assert.equal(shared[1].amountRaw,'10000000');
assert.equal(shared[1].sharedInputs,true);
assert.equal(shared[0].amountRaw,'4000000','outgoing per-address totals stay specific to their destination');
const sourceA='DdzFFzCqrhsk5m4Q8j6ou7gXoe6gotfoSpgT4P51ChoUP6R2ZQKBzF1JU5dXkiJg1u3JHfJSykHPyTp6ZZnEMXRpqcF4asQr7uDTqffo';
const sourceB='DdzFFzCqrhsur6w6gW7ocpi3NbxdS1HBtwfx7jcAcmv83k5zjd6nVg7WXMrhzDPhyWqrrdu24W8GLEdeCPwSRCRFvvGd2FWJz7pEPrRm';
const actual=analyse({tx_hash:'7dcbcfed0afcd0431f30ee8ead931ceb887f5f84056a8c6572e4f752442ca399',tx_timestamp:1649356185,fee:'183321',inputs:[io(sourceA,'2525996867'),io(sourceB,'18000000')],outputs:[io(own,'209174425'),io('external-change','2334639121')]},new Set([own]));
const assigned=normalizeCexAddresses([{address:sourceA,name:'Byron CEX'},{address:sourceB,name:'Byron CEX'}]);
assert.equal(assigned.length,2);
for(const address of [sourceA,sourceB]){
  const rows=byronAddressTransactions([actual],address,assigned);
  assert.equal(rows[0].amountRaw,'209174425');assert.equal(rows[0].sharedInputs,true);
}
assert.equal(cexAdaNetPosition([actual,actual],assigned,'0').receivedRaw,'209174425','received wallet amount, not the input sum; counted once');
assert.equal(byronAddressTransactions([actual],sourceB,[assigned[1]])[0].amountRaw,null,'unknown source must not silently become an exchange');
assert.deepEqual(saveByronSelection(group,[a,b],new Set([a]),'Renamed',[]),[{address:a,name:'Exchange'}]);
console.log('PASS: Byron discovery, explicit selection, persistence and grouped transfer deduplication.');
const renamed=saveByronSelection(group,[a,b],new Set([a,b]),'Default',[],{[a]:' My exchange ',[b]:'Second wallet'});
assert.deepEqual(renamed,[{address:a,name:'My exchange'},{address:b,name:'Second wallet'}]);
assert.equal(group[0].name,'Exchange','renaming does not mutate saved entries');
assert.deepEqual(normalizeCexAddresses(JSON.parse(JSON.stringify(renamed))),renamed);
assert.deepEqual(cexAdaNetPosition([buy,sell],renamed,'0'),cexAdaNetPosition([buy,sell],group,'0'));
assert.equal(saveByronSelection(group,[a],new Set([a]),'Default',[],{[a]:'   '})[0].name,'Exchange');
assert.equal(saveByronSelection([],[a],new Set([a]),'Default',[],{[a]:'New wallet'})[0].name,'New wallet');
assert.equal(saveByronSelection([],[a],new Set([a]),'Default',[],{[a]:'x'.repeat(100)})[0].name.length,60);
