import assert from 'node:assert/strict';
import {cexBtcSeries} from './cex-btc.ts';
import type {Fact} from './core.ts';
const time=Date.parse('2023-01-01')/1000;
const entries=[{address:'exchange',name:'Exchange'}];
const fact=(hash:string,side:'in'|'out',offset=0):Fact=>({hash,time:time+offset,adaRaw:side==='in'?'100000000':'-100000000',feeRaw:'0',internal:false,assets:{},decimals:{},wallets:[],swapCandidate:false,externalInputs:side==='in'?[{address:'exchange',lovelace:'100000000'}]:[],externalOutputs:side==='out'?[{address:'exchange',lovelace:'100000000'}]:[]});
const input=fact('a','in'),output=fact('b','out',86400);
const ada={'2023-01-01':0.5,'2023-01-02':1};
const btc={'2023-01-01':10000,'2023-01-02':20000};
const points=cexBtcSeries([input,output,input],entries,ada,btc);
assert.equal(points.length,2,'duplicate transaction counted once');
assert.equal(points[1].incoming,0.005);
assert.equal(points[1].outgoing,0.005,'each transfer uses its own dated BTC rate');
const missing=cexBtcSeries([input,output],entries,ada,{'2023-01-01':10000});
assert.equal(missing[1].outgoing,null,'missing prices never become zero');
assert.equal(missing[1].incoming,0.005,'missing outgoing price does not erase incoming');
assert.equal(missing[1].missing,1);
assert.equal(cexBtcSeries([input],entries,{},btc)[0].incoming,null);
console.log('PASS: historical BTC conversion, directions, deduplication and missing prices.');
