import assert from 'node:assert/strict';
import {base58} from '@scure/base';
import {compactBlock,expandBlock} from './compact-storage.ts';
import {encodeSolanaSettings,readSolanaSettings,compactSolanaSettings} from './solana-storage.ts';
import {solanaData,type SolanaTransaction} from './solana.ts';
import {prepareCheckpoint,restoreCheckpoint,type VaultData} from './vault-checkpoint.ts';
import {portfolioTransactionCounts} from './transaction-counts.ts';
import {sealVault,openVault} from './vault-crypto.ts';

const hash='a'.repeat(64);
const original={txs:[{tx_hash:hash,block_time:1700000000,block_height:1}],facts:{[hash]:{hash,time:1700000000,assets:{token:'12345678901234567890'},source:{addresses:['same','same'],flag:false,count:0,absent:null}}}};
const encoded=compactBlock(original);
assert.equal(encoded.strings.filter(value=>value===hash).length,1,'Cardano hash occurs once across transaction, map key and fact');
assert.deepEqual(expandBlock(encoded),original);
assert.throws(()=>expandBlock({...encoded,content:{s:encoded.strings.length}}),/Invalid/);
assert.deepEqual(expandBlock(original),original,'legacy Cardano blocks remain readable');
const address=base58.encode(new Uint8Array(32).fill(1));
const transactions:SolanaTransaction[]=Array.from({length:10001},(_,index)=>{
  const bytes=new Uint8Array(64).fill(2);new DataView(bytes.buffer).setUint32(0,index);
  return {hash:base58.encode(bytes),slot:index,time:1700000000+index,payer:address,feeRaw:'5000',failed:false,transfers:[{from:address,to:address,raw:'1000000000'}]};
});
const key='tdsp-member-solana-data:member';
const data={accounts:{[address]:{raw:'1000000000',slot:10001,checkpoint:null,transactions}},pending:[transactions[0]],history:{},usd:100};
const settings=encodeSolanaSettings(key,data);
assert.deepEqual(readSolanaSettings(key,name=>settings[name]??null),solanaData(data));
assert.deepEqual(compactSolanaSettings({[key]:JSON.stringify(data)}),settings,'retry upgrades fetched legacy SOL history');
settings['tdsp-member-solana-wallets:member']=JSON.stringify([{address,name:'SOL'}]);
const vault:VaultData={version:1,settings,snapshot:{key:'member::test',data:{...original,infos:[],markets:{},adaUsd:1,history:{},updated:'now',complete:true,priceAt:null} as any}};
const stake='stake1uxythldc4nmx45tvnwsqu4h5pyjd94udytm6f0tgnr44vecjd8vel';
const encryptionKey=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);
assert.deepEqual(expandBlock(await openVault(encryptionKey,stake,await sealVault(encryptionKey,stake,compactBlock(vault)))),vault,'shared format also restores local encrypted storage');
const checkpoint=await prepareCheckpoint(vault,encryptionKey,stake,null);
const restored=await restoreCheckpoint(checkpoint.index,encryptionKey,stake,async ids=>checkpoint.chunks.filter(row=>ids.includes(row.id)));
assert.deepEqual(restored,vault,'mixed ADA/SOL encrypted checkpoint restores all values');
assert.equal(portfolioTransactionCounts(restored,'member').total,10002);
assert.equal((await prepareCheckpoint(vault,encryptionKey,stake,checkpoint.index)).chunks.length,0,'unchanged blocks are reused');
const largeTransactions=Array.from({length:10001},(_,index)=>({tx_hash:index.toString(16).padStart(64,'0'),block_time:1700000000,block_height:index}));
const large:VaultData={version:1,settings:{},snapshot:{key:'member::large',data:{...vault.snapshot!.data,txs:largeTransactions,facts:{}}}};
const largeCheckpoint=await prepareCheckpoint(large,encryptionKey,stake,null);
assert.equal(Object.keys(largeCheckpoint.index.buckets).length,2,'large Cardano time buckets are partitioned');
const largeRestored=await restoreCheckpoint(largeCheckpoint.index,encryptionKey,stake,async ids=>largeCheckpoint.chunks.filter(row=>ids.includes(row.id)));
assert.equal(largeRestored.snapshot!.data.txs.length,10001);
assert.deepEqual(new Set(largeRestored.snapshot!.data.txs.map(tx=>tx.tx_hash)),new Set(largeTransactions.map(tx=>tx.tx_hash)));
delete settings[`${key}::${address}:1`];
assert.throws(()=>readSolanaSettings(key,name=>settings[name]??null),/incomplete/);
