import assert from 'node:assert/strict';
import {matchCrossChainSwaps} from './cross-chain-swaps.ts';
import {ethereumFees,type EthereumData,type EthereumTransaction} from './ethereum.ts';
import type {Fact} from './core.ts';
const time=Date.parse('2023-01-06T23:55:00Z')/1000,address='0x'+'a'.repeat(40),external='0x'+'b'.repeat(40);
const hash='0x'+'1'.repeat(64),wallets=[{address,name:'Swap',group:'swap' as const}];
const tx:EthereumTransaction={id:hash+':normal',hash,kind:'normal',block:1,time:time+600,from:external,to:address,valueWei:'1000000000000000000',feeWei:'210000000000000',failed:false};
const fact:Fact={hash:'ada',time,adaRaw:'-2002000000',feeRaw:'2000000',internal:false,assets:{},decimals:{},wallets:['swap'],swapCandidate:true,externalInputs:[],externalOutputs:[]};
const data:EthereumData={accounts:{[address]:{balanceWei:'1000000000000000000',block:1,transactions:[tx]}},history:{'2023-01-07':1000},usd:1000,updated:null};
const history={'2023-01-06':0.5};
const match=(facts=[fact],eth=data,ws=wallets)=>matchCrossChainSwaps(facts,new Set(['swap']),eth,ws,history);
assert.deepEqual([...match().cardano],['ada']);assert.deepEqual([...match().ethereum],[tx.id]);
const withTx=(change:Partial<EthereumTransaction>)=>({...data,accounts:{[address]:{...data.accounts[address],transactions:[{...tx,...change}]}}});
assert.equal(match([fact],withTx({time:time+601})).cardano.size,0,'ten-minute boundary');
assert.equal(match([fact],{...data,history:{'2023-01-07':950}}).cardano.size,1,'5% is included');
assert.equal(match([fact],{...data,history:{'2023-01-07':949}}).cardano.size,0,'over 5% is excluded');
assert.equal(match([fact],withTx({from:address,to:external})).cardano.size,0,'same-direction transfers do not match');
assert.equal(match([fact],withTx({failed:true})).cardano.size,0);
assert.equal(match([fact],{...data,history:{}}).cardano.size,0,'missing historical prices never become zero');
assert.equal(match([fact],data,[{address,name:'Regular'}] as any).cardano.size,0,'both chains need saved swap wallets');
assert.equal(match([{...fact,assets:{token:'1'}}]).cardano.size,0,'mixed token trades are not inferred');
assert.equal(match([fact,{...fact,hash:'other'}]).cardano.size,0,'ambiguous ADA candidates stay unlinked');
const duplicate={...tx,id:'0x'+'2'.repeat(64)+':normal',hash:'0x'+'2'.repeat(64)};
assert.equal(match([fact],{...data,accounts:{[address]:{...data.accounts[address],transactions:[tx,duplicate]}}}).cardano.size,0,'ambiguous ETH candidates stay unlinked');
const before=structuredClone({fact,data});match();assert.deepEqual({fact,data},before,'matching never mutates history or fees');
assert.equal(ethereumFees(withTx({from:address,to:external}),wallets),0.00021,'gas remains attributable');
console.log('PASS: cross-chain swap time/price boundaries, directions, scope, missing prices, ambiguity and immutable history.');
