import assert from 'node:assert/strict';
import {matchCrossChainSwaps,groupSwapRows} from './cross-chain-swaps.ts';
import {ethereumFees,ethereumTransactions,ethereumSwapDirection,type EthereumData,type EthereumTransaction} from './ethereum.ts';
import type {Fact} from './core.ts';
const time=Date.parse('2023-01-06T23:55:00Z')/1000,address='0x'+'a'.repeat(40),external='0x'+'b'.repeat(40);
const hash='0x'+'1'.repeat(64),wallets=[{address,name:'Swap',group:'swap' as const}];
const tx:EthereumTransaction={id:hash+':normal',hash,kind:'normal',block:1,time:time+600,from:external,to:address,valueWei:'1000000000000000000',feeWei:'210000000000000',failed:false};
const fact:Fact={hash:'ada',time,adaRaw:'-2002000000',feeRaw:'2000000',internal:false,assets:{},decimals:{},wallets:['swap'],swapCandidate:true,externalInputs:[],externalOutputs:[]};
const data:EthereumData={accounts:{[address]:{balanceWei:'1000000000000000000',block:1,transactions:[tx]}},history:{'2023-01-07':1000},usd:1000,updated:null};
const history={'2023-01-06':0.5};
const match=(facts=[fact],eth=data,ws=wallets)=>matchCrossChainSwaps(facts,new Set(['swap']),eth,ws,history);
assert.deepEqual([...match().cardano],['ada']);assert.deepEqual([...match().ethereum],[tx.id]);
assert.deepEqual(match().pairs,[{cardano:'ada',ethereum:tx.id}]);
const adaRow={chain:'cardano' as const,tx:{tx_hash:'ada'}},ethRow={chain:'ethereum' as const,tx:{id:tx.id}},otherRow={chain:'cardano' as const,tx:{tx_hash:'other'}};
assert.deepEqual(groupSwapRows([ethRow,otherRow,adaRow],match().pairs),[[adaRow,ethRow],[otherRow]],'paired legs share one row, ordered ADA then ETH');
assert.deepEqual(groupSwapRows([ethRow,otherRow],match().pairs),[[ethRow],[otherRow]],'filtered counterparts are not silently reintroduced');
const fillers=Array.from({length:99},(_,i)=>({chain:'cardano' as const,tx:{tx_hash:'filler'+i}}));
assert.deepEqual(groupSwapRows([...fillers,ethRow,adaRow],match().pairs).slice(0,100).at(-1),[adaRow,ethRow],'pagination cannot separate the pair');
const withTx=(change:Partial<EthereumTransaction>)=>({...data,accounts:{[address]:{...data.accounts[address],transactions:[{...tx,...change}]}}});
assert.equal(match([fact],withTx({time:time+601})).cardano.size,1,'delays over ten minutes now match');
assert.equal(match([fact],withTx({time:time+3600})).cardano.size,1,'sixty-minute boundary is included');
assert.equal(match([fact],withTx({time:time+3601})).cardano.size,0,'over sixty minutes is excluded');
const earlier=(seconds:number)=>({...withTx({time:time-seconds}),history:{'2023-01-06':1000}});
assert.equal(match([fact],earlier(3600)).cardano.size,1,'ETH may precede ADA by sixty minutes');
assert.equal(match([fact],earlier(3601)).cardano.size,0,'earlier ETH beyond sixty minutes is excluded');
assert.equal(match([fact],{...data,history:{'2023-01-07':950}}).cardano.size,1,'5% is included');
assert.equal(match([fact],{...data,history:{'2023-01-07':949}}).cardano.size,0,'over 5% is excluded');
assert.equal(match([fact],withTx({from:address,to:external})).cardano.size,0,'same-direction transfers do not match');
assert.equal(match([fact],withTx({failed:true})).cardano.size,0);
assert.equal(match([fact],{...data,history:{}}).cardano.size,0,'missing historical prices never become zero');
assert.equal(match([fact],data,[{address,name:'Regular'}] as any).cardano.size,0,'both chains need saved swap wallets');
assert.equal(match([{...fact,assets:{token:'1'}}]).cardano.size,0,'mixed token trades are not inferred');
assert.equal(match([fact,{...fact,hash:'other'}]).cardano.size,0,'ambiguous ADA candidates stay unlinked');
const duplicate={...tx,id:'0x'+'2'.repeat(64)+':normal',hash:'0x'+'2'.repeat(64)};
assert.equal(match([fact],{...data,accounts:{[address]:{...data.accounts[address],transactions:[tx,duplicate]}}}).cardano.size,0,'ambiguous ETH candidates stay unlinked');
const before=structuredClone({fact,data});match();assert.deepEqual({fact,data},before,'matching never mutates history or fees');
assert.equal(ethereumFees(withTx({from:address,to:external}),wallets),0.00021,'gas remains attributable');
const ownWallet={address:external,name:'Metamask'};
const bothWallets=[...wallets,ownWallet];
assert.equal(ethereumSwapDirection(tx,bothWallets),false,'regular wallet to saved Swap wallet is outgoing');
assert.equal(ethereumSwapDirection({...tx,from:address,to:external},bothWallets),true,'saved Swap wallet to regular wallet is incoming');
assert.equal(ethereumSwapDirection(tx,[ownWallet,{address,name:'Regular'}]),null,'ordinary self transfers are not swap legs');
assert.equal(ethereumSwapDirection(tx,[...wallets,{...ownWallet,group:'swap'}]),null,'transfers between two Swap wallets are not inferred');
const mayTime=Date.parse('2026-05-29T02:18:00Z')/1000;
const mayFact={...fact,time:mayTime,adaRaw:String(-Math.round(2461.90/0.232251*1e6)),feeRaw:null};
const mayTx={...tx,id:hash+':0',kind:'internal' as const,feeWei:null,time:mayTime+42*60,from:address,to:external,valueWei:'1226010640000000000'};
const mayData={...data,accounts:{[external]:{...data.accounts[address],transactions:[mayTx]},[address]:{...data.accounts[address],transactions:[mayTx]}},history:{'2026-05-29':2008.753681}};
const mayMatch=matchCrossChainSwaps([mayFact],new Set(['swap']),mayData,bothWallets,{'2026-05-29':0.232251});
assert.equal(mayMatch.pairs.length,1,'screenshot: 42-minute ADA send and internal ETH receipt are paired across the saved Swap boundary');
assert.deepEqual([...mayMatch.ethereum],[ethereumTransactions(mayData,bothWallets)[0].id],'pair uses the canonical internal trace ID');
const juneTime=Date.parse('2026-06-09T20:41:00Z')/1000;
const juneSend={...fact,hash:'june-send',time:juneTime,adaRaw:String(-Math.round(165.27/0.165241*1e6)),feeRaw:null};
const juneReceipt={...fact,hash:'june-receipt',time:juneTime+26*60,adaRaw:String(Math.round(161.19/0.165241*1e6)),feeRaw:null};
const juneMatch=matchCrossChainSwaps([juneSend,juneReceipt],new Set(['swap']),{...data,accounts:{}},[],{'2026-06-09':0.165241});
assert.deepEqual(juneMatch.pairs,[{cardano:'june-send',cardanoReturn:'june-receipt'}],'screenshot: same-chain swaps within 26 minutes and 5% share one pair');
assert.deepEqual(groupSwapRows([{chain:'cardano',tx:{tx_hash:'june-receipt'}},{chain:'cardano',tx:{tx_hash:'june-send'}}],juneMatch.pairs).map(group=>group.length),[2]);
assert.equal(juneMatch.cardano.size,2,'both ADA legs are excluded from CEX totals');
assert.equal(matchCrossChainSwaps([juneSend,{...juneReceipt,wallets:['another-swap']}],new Set(['swap','another-swap']),{...data,accounts:{}},[],{'2026-06-09':0.165241}).pairs.length,0,'different saved Swap addresses are not paired on amount alone');
console.log('PASS: cross-chain swap time/price boundaries, directions, scope, missing prices, ambiguity and immutable history.');
