import assert from 'node:assert/strict';
import {policyCollections,holdingTotal,policyTableRows,collectionName,collectionRepresentative} from './holding-groups.ts';
const policy='a'.repeat(56),other='b'.repeat(56);
const rows=[{id:'lovelace',value:25},{id:policy+'01',value:10},{id:policy+'02',value:20},{id:other+'01',value:null}];
const groups=policyCollections(rows);
assert.equal(groups.length,1);
assert.equal(groups[0].policy,policy);
assert.deepEqual(groups[0].assets,rows.slice(1,3));
assert.equal(holdingTotal(groups[0].assets,true),30);
assert.equal(holdingTotal(rows,true),55);
assert.equal(holdingTotal([],true),0);
assert.equal(holdingTotal([],false),null);
assert.equal(holdingTotal([{value:null}],true),null);
assert.equal(policyCollections([{id:'lovelace'},{id:'not-an-asset'}]).length,0);
const collapsed=policyTableRows(rows,new Set());
assert.equal(collapsed.length,3);
assert.deepEqual(collapsed[1],groups[0]);
const expanded=policyTableRows(rows,new Set([policy]));
assert.equal(expanded.length,5);
assert.deepEqual(expanded.slice(2,4),rows.slice(1,3).map(asset=>({asset})));
assert.equal(policyTableRows(rows,new Set(),row=>row.id==='lovelace').length,1);
assert.equal(policyTableRows(rows,new Set([policy]),row=>row.id===policy+'02').length,2);
assert.equal(collectionName('MallardOrder5160'),'MallardOrder');
assert.equal(collectionName('Starch Miner #01576'),'Starch Miner');
assert.equal(collectionName('Mfer3D0008'),'Mfer3D');
assert.equal(collectionName('Collection'),'Collection');
assert.equal(collectionName('123'),'123');
assert.equal(collectionRepresentative([{id:policy,name:policy},{id:policy+'ff',name:'Starch Miner #01576'}])?.name,'Starch Miner');
assert.equal(collectionRepresentative([{id:policy+'000de1404d616c6c6172644f7264657235313630',name:policy.slice(0,12)+'…'+policy.slice(-8)}])?.name,'MallardOrder');
assert.equal(collectionRepresentative([{id:policy+'ff',name:policy}])?.name,null);
assert.equal(collectionRepresentative([{id:policy,name:'asset1example'}])?.name,null);
console.log('PASS: policy grouping, singleton assets, ADA and incomplete valuation totals.');
