import assert from 'node:assert/strict';
import {learnMatchedSwapAddresses} from './matched-swap-addresses.ts';
import {memberWallets} from './member.ts';
import {swapAddressSet,trackedWalletAddresses} from './swap-wallets.ts';
import {ethereumWallets,ethereumSwapDirection,ethereumValue,type EthereumTransaction} from './ethereum.ts';
import type {Fact,Wallet} from './core.ts';

const stake='stake1uxythldc4nmx45tvnwsqu4h5pyjd94udytm6f0tgnr44vecjd8vel',root='stake1u8ryn5ws36v5npukuwahshtlf0u5l37hphxusx0m3rcyd9q7tcygp';
const owned='addr1qx305ezuv38ltzrk6kqspakj55l4mv7zmzzauypv530guyygh07m3t8kdtgkexaqpet0gzfy6ttc6ghh5j7k3x8t2ens7pgdc0';
const service='addr1qy687p9vy7p50qudx7p52evga9kwdm0l6lkvl2px5mgedjkxf8gapr5efxredcam0pwh7jleflrawrwdeqvlhz8sg62q8wmmps';
const wallets:Wallet[]=[{address:stake,label:'My wallet'},{address:root,label:'Simple Swap',group:'swap'}];
const fact:Fact={hash:'ada',time:1780021100,adaRaw:'-10600173333',feeRaw:'173333',internal:false,assets:{},decimals:{},wallets:[owned],swapCandidate:true,externalOutputs:[{address:service,stakeAddress:root,lovelace:'10600000000'}]};
const ethRoot='0x'+'a'.repeat(40),ethSource='0x'+'c'.repeat(40),hash='0x'+'1'.repeat(64);
const tx:EthereumTransaction={id:hash+':normal',hash,block:1,time:1780023611,from:ethSource,to:ethRoot,valueWei:'1000000000000000000',feeWei:'21000',kind:'normal',failed:false};
const ethWallets=[{address:ethRoot,name:'Simple Swap',group:'swap' as const}];
const data={accounts:{[ethRoot]:{block:1,balanceWei:'1000000000000000000',transactions:[tx]}},history:{},usd:2000,updated:null};
const pairs=[{cardano:'ada',ethereum:tx.id}],before=structuredClone({wallets,ethWallets,fact,data});
const learned=learnMatchedSwapAddresses(pairs,[fact],wallets,{},new Set([owned]),data,ethWallets);
assert.deepEqual(learned.cardano[1].swapAddresses,[service]);
assert.deepEqual(learned.ethereum[0].swapAddresses,[ethSource]);
assert.equal(learned.cardano.length,wallets.length);assert.equal(learned.ethereum.length,ethWallets.length,'counterparties do not become newly scanned wallets');
assert.deepEqual({wallets,ethWallets,fact,data},before,'learning preserves facts, cache and original settings');
const restored=memberWallets(stake,JSON.parse(JSON.stringify(learned.cardano)));
assert.deepEqual(restored[1].swapAddresses,[service]);
assert.deepEqual(ethereumWallets(JSON.parse(JSON.stringify(learned.ethereum))),learned.ethereum);
const again=learnMatchedSwapAddresses(pairs,[fact],learned.cardano,{},new Set([owned]),data,learned.ethereum);
assert.equal(again.cardano,learned.cardano);assert.equal(again.ethereum,learned.ethereum,'repeated matching is idempotent');
assert.ok(swapAddressSet(restored).has(service));
assert.ok(!trackedWalletAddresses(restored,{[stake]:[owned]}).includes(service),'linked services are not owned addresses');
assert.equal(ethereumValue(data,learned.ethereum),2000,'only the original owned balance contributes');
assert.equal(ethereumSwapDirection(tx,learned.ethereum),true,'learning must not break the original match direction');
assert.equal(learnMatchedSwapAddresses([], [fact],wallets,{},new Set([owned]),data,ethWallets).cardano,wallets,'unmatched transactions do not teach addresses');
assert.equal(learnMatchedSwapAddresses(pairs,[fact],wallets,{},new Set([owned,service]),data,ethWallets).cardano,wallets,'owned Cardano addresses never become service links');
const mixed={...fact,externalOutputs:[...fact.externalOutputs!,{address:owned,lovelace:'10'}]};
assert.equal(learnMatchedSwapAddresses(pairs,[mixed],wallets,{},new Set(),data,ethWallets).cardano,wallets,'multiple possible counterparties are not guessed');
console.log('PASS: matched Swap address learning, persistence, idempotence and unchanged ownership/scanning scope.');
