import assert from 'node:assert/strict';
import {availableTotal,ethereumAvailableTotals,availableCexResult} from './portfolio-totals.ts';
import {emptyEthereum,type EthereumData} from './ethereum.ts';
assert.deepEqual(availableTotal([100,null]),{value:100,partial:true});
assert.deepEqual(availableTotal([null]),{value:null,partial:true});
assert.deepEqual(availableTotal([0,0]),{value:0,partial:false});
const address='0x'+'a'.repeat(40),other='0x'+'b'.repeat(40),wallets=[{address,name:'Known'},{address:other,name:'Pending'}];
const data:EthereumData={...emptyEthereum(),usd:2000,accounts:{[address]:{balanceWei:'1000000000000000000',block:1,transactions:[]}}};
assert.deepEqual(ethereumAvailableTotals(data,wallets),{value:2000,partial:true,fees:0,feesPartial:true,feeUsd:0});
assert.equal(ethereumAvailableTotals({...data,usd:null},wallets).value,null);
assert.equal(ethereumAvailableTotals({...data,usd:null,accounts:{[address]:{...data.accounts[address],balanceWei:'0'}}},[wallets[0]]).value,0,'zero ETH holdings do not need a quote');
assert.equal(ethereumAvailableTotals(emptyEthereum(),wallets).fees,null,'unknown history is not zero gas');
const time=Date.parse('2023-01-06')/1000,rows=[{hash:'known',time,side:'buy' as const,usd:100},{hash:'unknown',time,side:'sell' as const,usd:null}];
assert.deepEqual(availableCexResult(rows,2000,'USD',0.5,{}, {},time),{value:1900,partial:true});
assert.deepEqual(availableCexResult(rows,2000,'ADA',0.5,{'2023-01-06':0.5},{},time),{value:3800,partial:true});
assert.deepEqual(availableCexResult(rows,2000,'EUR',0.5,{}, {'2023-01-06':{EUR:0.9}},time),{value:1710,partial:true});
assert.deepEqual(availableCexResult(rows,2000,'JPY',0.5,{}, {'2023-01-06':{JPY:130}},time),{value:247000,partial:true});
assert.deepEqual(availableCexResult(rows,null,'USD',0.5,{}, {},time),{value:null,partial:true},'unknown holdings cannot yield a gain from cash flows alone');
assert.deepEqual(availableCexResult(rows,2000,'EUR',0.5,{}, {},time),{value:null,partial:true},'missing FX rates never invent a converted amount');
console.log('PASS: available portfolio amounts, missing accounts/prices, zero ETH, gas coverage and dated CEX currencies.');
