import assert from 'node:assert/strict';
import {analyseAndCache,planRefresh} from './refresh-plan.ts';
import {needsFactRefresh} from './fact-refresh.ts';
import {createHistoryIndex} from './history-index.ts';
import type {Snapshot} from './cache';
import type {Detail} from './core';
const detail:Detail={tx_hash:'transfer',tx_timestamp:100,fee:'2',inputs:[{value:'100',payment_addr:{bech32:'a'},tx_hash:'input',tx_index:0}],outputs:[{value:'98',payment_addr:{bech32:'b'}}],marketplace_version:3};
const independent={...detail,tx_hash:'independent',outputs:[{value:'98',payment_addr:{bech32:'external'}}]};
const cached:Snapshot={groups:{wallet:['a']},infos:[],txs:[detail,independent].map(d=>({tx_hash:d.tx_hash,block_time:d.tx_timestamp,block_height:1})),facts:{transfer:analyseAndCache(detail,new Set(['a'])),independent:analyseAndCache(independent,new Set(['a']))},markets:{},adaUsd:1,history:{},updated:'now',complete:true,priceAt:null};
const unchanged=planRefresh(cached,{wallet:['a']});
assert.equal(unchanged.facts.transfer,cached.facts.transfer);
assert.equal(Object.values(unchanged.facts).filter(needsFactRefresh).length,0,'complete cached facts need no tx_info requests');
assert.equal(unchanged.batches[0].incremental,true);
const expanded=planRefresh(cached,{wallet:['a','b']});
assert.equal(expanded.facts.transfer.internal,true);
assert.equal(expanded.facts.transfer.adaRaw,'-2');
assert.equal(expanded.facts.independent,cached.facts.independent,'unaffected facts stay intact');
assert.equal(expanded.batches[0].incremental,true);
assert.deepEqual(expanded.batches[1],{addresses:['b'],incremental:false,newAddresses:true});
const index=createHistoryIndex(expanded.txs,true);
assert.equal(index.add(expanded.txs,true).reachedSavedHistory,true);
assert.equal(index.add(expanded.txs,false).reachedSavedHistory,false,'new addresses must scan past overlap with old history');
const combined={...cached,groups:{wallet:['a','b']},facts:expanded.facts};
const reduced=planRefresh(combined,{wallet:['a']});
assert.equal(reduced.facts.transfer.adaRaw,'-100');
assert.equal(reduced.facts.transfer.internal,false);
const replaced=planRefresh(cached,{wallet:['b']});
assert.equal(replaced.facts.transfer.adaRaw,'98');
assert.equal(replaced.txs.length,1);
const legacy=structuredClone(cached);delete legacy.facts.transfer.source;delete legacy.facts.independent.source;
const upgrade=planRefresh(legacy,{wallet:['a','b']});
assert.equal(upgrade.facts.transfer,undefined,'affected derived-only cache needs one detail fetch');
assert.equal(upgrade.facts.independent,legacy.facts.independent,'unaffected old-format facts are preserved');
assert.equal(planRefresh({...cached,complete:false},{wallet:['a']}).batches[0].incremental,false);
assert.equal(planRefresh(null,{wallet:['a']}).txs.length,0);
const interrupted={...legacy,groups:{wallet:['a','b']},complete:false,pendingOwnershipAddresses:['b']};
assert.equal(planRefresh(interrupted,interrupted.groups).batches.find(batch=>batch.addresses.includes('b'))?.newAddresses,true,'interrupted ownership scans resume safely');
assert.equal(cached.facts.transfer.adaRaw,'-100','planning never mutates the stored snapshot');
console.log('PASS: unchanged cache reuse, ownership reclassification, new address history, legacy gaps and removed wallets.');
