import assert from 'node:assert/strict';
import {liveAdaBasis,remainingBasis} from './core.ts';
import {holdingValue} from './valuation.ts';
import type {Fact} from './core.ts';
const base:Fact={hash:'a',time:1704067200,adaRaw:'100000000',assets:{},decimals:{},feeRaw:'0',internal:false,wallets:[],swapCandidate:true};
const spent={...base,hash:'b',time:1704153600,adaRaw:'-90000000'};
const received={...base,hash:'c',time:1704240000};
const history={'2024-01-01':2,'2024-01-02':2,'2024-01-03':0.2};
const facts=[base,spent,received];
const during=liveAdaBasis(facts,history,'110000000',false);
const after=liveAdaBasis(facts,history,'110000000',true);
assert.equal(during.usd,40);
assert.equal(after.usd,during.usd);
assert.equal(holdingValue('110000000',6,1,null,during).pnl,70);
assert.equal(during.reconciled,true);
assert.equal(during.provisional,true);
assert.equal(after.provisional,false);
assert.equal(liveAdaBasis([received],history,'110000000',false).usd,null);
assert.equal(liveAdaBasis(facts,{},'110000000',false).usd,null);
const token={...base,adaRaw:'-10000000',assets:{token:'2'},decimals:{token:0}};
const tokenBasis=remainingBasis([token],history).token;
assert.equal(holdingValue('2',0,12,null,tokenBasis).pnl,4);
assert.equal(holdingValue('3',0,12,null,tokenBasis).pnl,null);
assert.deepEqual(remainingBasis([token,token],history).token,tokenBasis);
const earlierSale={...token,hash:'earlier-sale',time:1703980800,assets:{token:'-1'}};
assert.equal(remainingBasis([earlierSale,token],history).token.usd,null);
console.log('Refresh valuation remains consistent before and after completion');
