import assert from 'node:assert/strict';
import {base58,bech32} from '@scure/base';
import {encode,Tagged} from 'cborg';
import CRC32 from 'crc-32';
import {addSwapWallet,trackedWalletAddresses,excludeInternalExchanges,swapOwnershipScope,resolveSwapGroups,exchangeExcludedAddresses,swapAddressSet,isSwapTransaction} from './swap-wallets.ts';
import {memberWallets,resolveWalletGroups} from './member.ts';
import {analyseAndCache,planRefresh} from './refresh-plan.ts';
import {cexAdaTransfer} from './cex.ts';
import {discoveredByronAddresses} from './byron-exchanges.ts';

const stake=bech32.encode('stake',bech32.toWords(Uint8Array.from([0xe1,...Array(28).fill(1)])),200);
const normal=bech32.encode('addr',bech32.toWords(Uint8Array.from([0x61,...Array(28).fill(2)])),200);
const payload=encode([new Uint8Array(28).fill(3),new Map(),0]);
const byron=base58.encode(encode([new Tagged(24,payload),CRC32.buf(payload)>>>0]));
let wallets=addSwapWallet(memberWallets(stake,[]),` ${byron} `);
wallets=addSwapWallet(wallets,normal.toUpperCase());
assert.deepEqual(memberWallets(stake,JSON.parse(JSON.stringify(wallets))),wallets);
assert.equal(wallets[1].address,byron);
assert.equal(wallets[2].address,normal);
assert.equal(wallets[1].label,'Swap');
assert.throws(()=>addSwapWallet(wallets,byron),/already included/);
assert.throws(()=>addSwapWallet(wallets,'invalid'),/valid mainnet/);
assert.throws(()=>addSwapWallet(wallets,stake),/already included/);
assert.deepEqual(resolveWalletGroups(wallets,[{stake_address:stake,addresses:[]}]),{[stake]:[]});
assert.notEqual(swapOwnershipScope(wallets),swapOwnershipScope([]));
assert.deepEqual(memberWallets(stake,[{address:byron,label:'Swap',group:'swap',ownsAddress:true}])[1],{address:byron,label:'Swap',group:'swap'});
// Swap labels do not override addresses independently resolved from the owned stake key.
assert.deepEqual(resolveWalletGroups(wallets,[{stake_address:stake,addresses:[normal]}]),{[stake]:[normal]});
const groups=resolveWalletGroups([{address:byron},{address:normal}],[]);
const owned=trackedWalletAddresses(wallets,groups);
assert.ok(owned.includes(byron)&&owned.includes(normal));
const entries=[{address:byron,name:'Byron CEX'},{address:normal,name:'Exchange'},{address:'external',name:'Other'}];
assert.deepEqual(excludeInternalExchanges(entries,owned),[entries[2]]);
const io=(address:string,value:string)=>({payment_addr:{bech32:address},value});
const detail={tx_hash:'swap',tx_timestamp:1,fee:'200000',inputs:[io(byron,'10000000')],outputs:[io(normal,'9800000')]};
const old=analyseAndCache(detail,new Set([normal]));
assert.equal(cexAdaTransfer(old,entries)?.side,'buy');
const plan=planRefresh({facts:{swap:old},txs:[{tx_hash:'swap',block_time:1}],groups:{[normal]:[normal]},complete:true} as any,groups);
assert.equal(plan.facts.swap.internal,true);
assert.equal(plan.facts.swap.adaRaw,'-200000');
assert.equal(cexAdaTransfer(plan.facts.swap,excludeInternalExchanges(entries,owned)),null);
assert.equal(discoveredByronAddresses([old],owned,entries).some(row=>row.address===byron),false);
assert.equal(plan.batches.find(batch=>batch.addresses.includes(byron))?.incremental,false);
assert.equal(plan.batches.find(batch=>batch.addresses.includes(normal))?.incremental,true);
console.log('Swap wallets: persistence, validation, internal transfers and CEX exclusion passed.');

// A shared sender must not convert the member receipt into the other output's amount.
const sender='addr1v8qtg8wsfv8vqky8xfsr7x9nwyjdsz5c2p05vyd2zjheu7qvax8ad';
const recipient='addr1qya8a5majq3ttgvxgr9sh3nhv0jn0e0zemacdkw63qp20j9ks6tde9vhwlml0j75jdh7rff4mxcrneyll72zhszd28lqfhtxjm';
const other='addr1v8mn6dmk7tf9u26kr09a05lmvc9j4k9d940a88ta3hdczqgyt7whl';
const hash='520c53702a98433f6e7a907fc2ac3be1c1b5797ecc0c291b940f62ceb014df68';
const tx={tx_hash:hash,tx_timestamp:1788908579,fee:'197381',inputs:[io(sender,'5299835643')],outputs:[io(recipient,'4631268208'),io(other,'668370054')]};
const wrong=analyseAndCache(tx,new Set([sender,recipient]));
assert.equal(wrong.adaRaw,'-668567435');
const labels=addSwapWallet(memberWallets(stake,[]),sender);
const fixedGroups=resolveWalletGroups(labels,[{stake_address:stake,addresses:[recipient]}]);
const unrelated=analyseAndCache({...tx,tx_hash:'unrelated',outputs:[io(other,'5299638262')]},new Set([sender,recipient]));
const repaired=planRefresh({groups:{[stake]:[recipient],[sender]:[sender]},facts:{[hash]:wrong,unrelated},txs:[{tx_hash:hash,block_time:tx.tx_timestamp},{tx_hash:'unrelated',block_time:1}],complete:true} as any,fixedGroups);
assert.equal(repaired.facts[hash].adaRaw,'4631268208');
assert.equal(repaired.facts[hash].hash,hash);
assert.equal(repaired.facts[hash].feeRaw,null);
assert.equal(repaired.facts[hash].internal,false);
assert.equal(repaired.facts[hash].source?.outputs[1].value,'668370054');
assert.equal(repaired.txs.length,1);
assert.ok(repaired.batches.every(batch=>!batch.addresses.includes(sender)));
assert.equal(excludeInternalExchanges([{address:sender,name:'CEX'}],trackedWalletAddresses(labels,fixedGroups)).length,0);
console.log('PASS: shared Swap receipt remains 4,631.268208 ADA at its original hash; unrelated transactions removed.');

const swapStake=bech32.encode('stake',bech32.toWords(Uint8Array.from([0xe1,...Array(28).fill(4)])),200);
const withStake=addSwapWallet(memberWallets(stake,[]),swapStake.toUpperCase());
assert.equal(withStake[1].address,swapStake);
assert.deepEqual(memberWallets(stake,JSON.parse(JSON.stringify(withStake))),withStake);
const accounts=[{stake_address:stake,addresses:[recipient]},{stake_address:swapStake,addresses:[sender,other,sender]}];
const ownedGroups=resolveWalletGroups(withStake,accounts);
const swapGroups=resolveSwapGroups(withStake,accounts);
assert.deepEqual(ownedGroups,{[stake]:[recipient]});
assert.deepEqual(swapGroups,{[swapStake]:[sender,other]});
const exclusions=exchangeExcludedAddresses(withStake,ownedGroups,swapGroups);
assert.deepEqual(excludeInternalExchanges([{address:sender},{address:other},{address:swapStake},{address:'unrelated'}],exclusions),[{address:'unrelated'}]);
assert.equal(analyseAndCache(tx,new Set(Object.values(ownedGroups).flat())).adaRaw,'4631268208');
assert.throws(()=>resolveSwapGroups(withStake,[accounts[0]]),/completely/);
assert.throws(()=>resolveSwapGroups(withStake,[{stake_address:swapStake,addresses:['invalid']}]),/completely/);
assert.deepEqual(resolveSwapGroups(withStake,[{stake_address:swapStake,addresses:[]}]),{[swapStake]:[]});
assert.ok(!exchangeExcludedAddresses(memberWallets(stake,[]),ownedGroups,swapGroups).includes(sender));
assert.deepEqual(JSON.parse(JSON.stringify({groups:ownedGroups,swapGroups})).swapGroups,swapGroups);
console.log('PASS: Swap stake addresses resolve and cache exclusions separately from wallet ownership.');
const receipt=repaired.facts[hash];
const original=JSON.stringify(receipt);
assert.equal(isSwapTransaction(receipt,swapAddressSet(labels)),true);
assert.equal(isSwapTransaction(receipt,swapAddressSet(withStake,swapGroups)),true);
assert.equal(isSwapTransaction({...receipt,source:undefined,externalInputs:[{address:sender,lovelace:'5299835643',stakeAddress:swapStake}]},swapAddressSet(withStake)),true);
assert.equal(isSwapTransaction(receipt,new Set(['unrelated'])),false);
assert.equal(isSwapTransaction(undefined,swapAddressSet(labels)),false);
assert.equal(JSON.stringify(receipt),original);
assert.equal(receipt.adaRaw,'4631268208');
console.log('PASS: Swap type matches direct/resolved/stake addresses without changing transaction amounts.');
