import assert from 'node:assert/strict';
import {base58,bech32} from '@scure/base';
import {encode,Tagged} from 'cborg';
import CRC32 from 'crc-32';
import {addSwapWallet,trackedWalletAddresses,excludeInternalExchanges} from './swap-wallets.ts';
import {memberWallets,resolveWalletGroups} from './member.ts';
import {analyseAndCache,planRefresh} from './refresh-plan.ts';
import {cexAdaTransfer} from './cex.ts';
import {discoveredByronAddresses} from './byron-exchanges.ts';

const stake=bech32.encode('stake',bech32.toWords(Uint8Array.from([0xe1,...Array(28).fill(1)])),200);
const normal=bech32.encode('addr',bech32.toWords(Uint8Array.from([0x61,...Array(28).fill(2)])),200);
const payload=encode([new Uint8Array(28).fill(3),new Map(),0]);
const byron=base58.encode(encode([new Tagged(24,payload),CRC32.buf(payload)>>>0]));
let wallets=addSwapWallet(memberWallets(stake,[]),` ${byron} `);
wallets=addSwapWallet(wallets,normal.toUpperCase());
assert.deepEqual(memberWallets(stake,JSON.parse(JSON.stringify(wallets))),wallets);
assert.equal(wallets[1].address,byron);
assert.equal(wallets[2].address,normal);
assert.equal(wallets[1].label,'Swap');
assert.throws(()=>addSwapWallet(wallets,byron),/already included/);
assert.throws(()=>addSwapWallet(wallets,'invalid'),/valid mainnet/);
assert.throws(()=>addSwapWallet(wallets,stake),/valid mainnet/);
const groups=resolveWalletGroups(wallets,[{stake_address:stake,addresses:[]}]);
const owned=trackedWalletAddresses(wallets,groups);
assert.ok(owned.includes(byron)&&owned.includes(normal));
const entries=[{address:byron,name:'Byron CEX'},{address:normal,name:'Exchange'},{address:'external',name:'Other'}];
assert.deepEqual(excludeInternalExchanges(entries,owned),[entries[2]]);
const io=(address:string,value:string)=>({payment_addr:{bech32:address},value});
const detail={tx_hash:'swap',tx_timestamp:1,fee:'200000',inputs:[io(byron,'10000000')],outputs:[io(normal,'9800000')]};
const old=analyseAndCache(detail,new Set([normal]));
assert.equal(cexAdaTransfer(old,entries)?.side,'buy');
const plan=planRefresh({facts:{swap:old},txs:[{tx_hash:'swap',block_time:1}],groups:{[normal]:[normal]},complete:true} as any,groups);
assert.equal(plan.facts.swap.internal,true);
assert.equal(plan.facts.swap.adaRaw,'-200000');
assert.equal(cexAdaTransfer(plan.facts.swap,excludeInternalExchanges(entries,owned)),null);
assert.equal(discoveredByronAddresses([old],owned,entries).some(row=>row.address===byron),false);
assert.equal(plan.batches.find(batch=>batch.addresses.includes(byron))?.incremental,false);
assert.equal(plan.batches.find(batch=>batch.addresses.includes(normal))?.incremental,true);
console.log('Swap wallets: persistence, validation, internal transfers and CEX exclusion passed.');
