import assert from 'node:assert/strict';
import {transferComparison,comparisonNet,fiatRate} from './transfer-comparison.ts';
import type {Fact} from './core.ts';
const time=Date.parse('2023-01-06')/1000;
const entries=[{address:'exchange',name:'Exchange'}];
const fact=(hash:string,side:'in'|'out',offset=0):Fact=>({hash,time:time+offset,adaRaw:side==='in'?'100000000':'-100000000',feeRaw:'0',internal:false,assets:{},decimals:{},wallets:[],swapCandidate:false,externalInputs:side==='in'?[{address:'exchange',lovelace:'100000000'}]:[],externalOutputs:side==='out'?[{address:'exchange',lovelace:'100000000'}]:[]});
const input=fact('a','in'),output=fact('b','out',86400);
const ada={'2023-01-06':0.5,'2023-01-07':1};
const btc={'2023-01-06':10000,'2023-01-07':20000};
const fx={'2023-01-06':{EUR:0.9,JPY:130}};
const points=transferComparison([input,output,input],entries,ada,btc,fx,'BTC','EUR');
assert.equal(points.length,2,'duplicate transaction counted once');
assert.deepEqual(points.at(-1),{time:time+86400,incoming:0.005,outgoing:0.005,inFiat:45,outFiat:90});
assert.equal(fiatRate(time+86400,'EUR',fx),0.9,'weekend uses prior business day');
assert.equal(fiatRate(time+7*86400,'EUR',fx),null,'stale FX not reused');
assert.equal(fiatRate(time,'USD',{}),1);
const net=comparisonNet(points.at(-1),50,1,btc,fx,'BTC','EUR',time+86400);
assert.ok(Math.abs(net.amount!-0.0025)<1e-12);assert.equal(net.fiat,90);
const yen=transferComparison([input,output],entries,ada,btc,fx,'ADA','JPY').at(-1)!;
assert.equal(yen.incoming,100);assert.equal(yen.outgoing,100);
assert.equal(yen.inFiat,6500);assert.equal(yen.outFiat,13000);
const missing=transferComparison([input,output],entries,ada,{'2023-01-06':10000},fx,'BTC','USD').at(-1)!;
assert.equal(missing.outgoing,null,'missing price is not zero');assert.equal(missing.incoming,0.005);
assert.equal(transferComparison([input],entries,ada,btc,{},'ADA','EUR')[0].inFiat,null);
assert.equal(transferComparison([input],entries,{},btc,fx,'BTC','USD')[0].incoming,null);
console.log('PASS: crypto/fiat selection, dated prices, weekend FX, deduplication, net balances and missing rates.');
