import assert from 'node:assert/strict';
import {matchesTransaction,matchesSearchText} from './transaction-search.ts';
import type {Fact} from './core.ts';
const id='a'.repeat(56)+Buffer.from('MallardOrder1176').toString('hex');
const fact:Fact={hash:'abcdef',time:1,adaRaw:'0',assets:{[id]:'1'},decimals:{},feeRaw:null,internal:false,wallets:['own'],swapCandidate:true};
for(const query of ['MallardOrder1176','mallard','Mallard Order #1176','1176',' ABCDEF ',' Savings ',''])assert.equal(matchesTransaction(query,fact.hash,fact,{},[{address:'own',label:'Savings'}]),true);
assert.equal(matchesTransaction('other NFT',fact.hash,fact,{},[]),false);
assert.equal(matchesTransaction('Mallard',fact.hash,undefined,{},[]),false);
assert.equal(matchesTransaction('ABC',fact.hash,undefined,{},[]),true);
assert.equal(matchesTransaction('DUCK',fact.hash,fact,{[id]:{token_id:id,ticker:'DUCK'}},[]),true);
console.log('Transaction asset-name, ticker, hash and wallet search passed');
const policy='6c0394ebf4b6d7ed9709cf901863c254448a40785819a57f7c39a130';
const bundle={...fact,hash:'fc77d1402b6856568ebe899388225857822a12f4589432c3f398c046cbfbcf0e',assets:Object.fromEntries(['DaggerofSacrilege999','AmuletofInfluence2022','SpearofCircumstance1251','RingofInvocation1669','CupOfConfusionAndIntellect383'].map(name=>[policy+Buffer.from(name).toString('hex'),'1']))};
assert.equal(matchesTransaction('AmuletofInfluence2022',bundle.hash,bundle,{},[]),true);
assert.equal(matchesTransaction('Amulet of Influence 2022',bundle.hash,bundle,{},[]),true);
const swapWallets=[{address:'own',label:'Savings'},{address:'service',label:'My Swap',group:'swap' as const}];
const swapReceipt={...fact,externalInputs:[{address:'service',lovelace:'1000000'}]};
assert.equal(matchesTransaction('my swap',fact.hash,swapReceipt,{},swapWallets),true);
assert.equal(matchesTransaction('my swap',fact.hash,fact,{},swapWallets),false);
const sourceReceipt={...fact,externalInputs:[{address:'service',lovelace:'1000000'}]};
const exchanges=[{address:'service',name:'My Services Source'},{address:'unrelated',name:'Other Exchange'}];
assert.equal(matchesTransaction(' SERVICES ',fact.hash,sourceReceipt,{},[],exchanges),true);
assert.equal(matchesTransaction('my-services-source',fact.hash,sourceReceipt,{},[],exchanges),true);
assert.equal(matchesTransaction('other exchange',fact.hash,sourceReceipt,{},[],exchanges),false);
assert.equal(matchesTransaction('services',fact.hash,undefined,{},[],exchanges),false);
assert.equal(matchesTransaction('SECOND LABEL',fact.hash,fact,{},[{address:'own',label:'Savings'},{address:'own',label:'Second Label'}]),true);
assert.equal(matchesTransaction('my-services-source',fact.hash,{...sourceReceipt,externalInputs:[{address:'payment',stakeAddress:'service',lovelace:'1000000'}]}, {},[],exchanges),true);
for(const name of ['ETH Savings','SOL Savings']){
  assert.equal(matchesSearchText(name.toUpperCase(),[name]),true);
  assert.equal(matchesSearchText(name.replace(' ','-'),[name]),true);
  assert.equal(matchesSearchText('ＳＡＶＩＮＧＳ',[name]),true);
}
assert.equal(matchesSearchText('Other Wallet',['SOL Savings']),false);
assert.equal(matchesTransaction('my swap',fact.hash,{...fact,source:{tx_hash:fact.hash,tx_timestamp:1,fee:'0',inputs:[{payment_addr:{bech32:'service'},value:'1000000'}],outputs:[]}}, {},swapWallets),true);
