import assert from 'node:assert/strict';
import {prepareCheckpoint,restoreCheckpoint,type VaultData} from './vault-checkpoint.ts';
import {openVault} from './vault-crypto.ts';
const stake='stake1uxythldc4nmx45tvnwsqu4h5pyjd94udytm6f0tgnr44vecjd8vel';
const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);
const a='a'.repeat(64),b='b'.repeat(64);
const data:VaultData={version:1,settings:{private:'secret'},snapshot:{key:stake+'::test',data:{infos:[],txs:[{tx_hash:a,block_time:1700000000},{tx_hash:b,block_time:1600000000}] as any,facts:{[a]:{fee:'123'}} as any,markets:{},adaUsd:1,history:{},updated:'now',complete:false,priceAt:null}}};
const first=await prepareCheckpoint(data,key,stake,null);
assert.equal(first.chunks.length,2);
assert.deepEqual(await openVault(key,stake,first.payload),first.index);
const identical=await prepareCheckpoint(data,key,stake,first.index);
assert.equal(identical.chunks.length,0);
data.settings.private='new';
assert.equal((await prepareCheckpoint(data,key,stake,first.index)).chunks.length,0);
data.snapshot!.data.facts[b]={fee:'456'} as any;
const changed=await prepareCheckpoint(data,key,stake,first.index);
assert.equal(changed.chunks.length,1);
const rows=[...first.chunks,...changed.chunks];
const restored=await restoreCheckpoint(changed.index,key,stake,async ids=>rows.filter(row=>ids.includes(row.id)));
assert.deepEqual(restored,data);
await assert.rejects(restoreCheckpoint(changed.index,key,stake,async()=>[]),/incomplete/);
const tampered=structuredClone(changed.index);Object.values(tampered.buckets)[0].digest='0'.repeat(64);
await assert.rejects(restoreCheckpoint(tampered,key,stake,async ids=>rows.filter(row=>ids.includes(row.id))),/integrity/);
await assert.rejects(prepareCheckpoint(data,key,stake,null,AbortSignal.abort()),{name:'AbortError'});
console.log('PASS: incremental buckets, settings-only checkpoints, roundtrip, integrity and cancellation.');
