import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {encode} from 'cborg';
import {bech32} from '@scure/base';
import {blake2b} from '@noble/hashes/blake2.js';
import {deriveVaultKey,unlockMessage,openVault,sealVault} from './vault-crypto.ts';
const {privateKey,publicKey}=generateKeyPairSync('ed25519');
const pub=new Uint8Array(publicKey.export({type:'spki',format:'der'}).subarray(-32));
const stake=bech32.encode('stake',bech32.toWords(Uint8Array.from([0xe1,...blake2b(pub,{dkLen:28})])));
const address=bech32.fromWords(bech32.decode(stake,200).words);
const headers=encode(new Map([[1,-8],['address',address]] as any));
const payload=new TextEncoder().encode(unlockMessage(stake));
const sig=sign(null,encode(['Signature1',headers,new Uint8Array(),payload]),privateKey);
const signed={signature:Buffer.from(encode([headers,new Map([['hashed',false]]),payload,sig])).toString('hex'),key:Buffer.from(encode(new Map([[1,1],[3,-8],[-1,6],[-2,pub]] as any))).toString('hex')};
const key=await deriveVaultKey(stake,signed),sameKey=await deriveVaultKey(stake,signed);
assert.equal(key.extractable,false);
const data={version:1,settings:{secret:'private label'},snapshot:{facts:'test'}};
const envelope=await sealVault(key,stake,data);
assert.deepEqual(await openVault(sameKey,stake,envelope),data);
assert.ok(!JSON.stringify(envelope).includes('private label'));
assert.notEqual((await sealVault(key,stake,data)).iv,envelope.iv);
const wrong=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);
await assert.rejects(openVault(wrong,stake,envelope));
await assert.rejects(openVault(key,stake,{...envelope,ciphertext:envelope.ciphertext.replace(/^./,envelope.ciphertext[0]==='A'?'B':'A')}));
await assert.rejects(deriveVaultKey(stake,{...signed,signature:'00'}));
await assert.rejects(deriveVaultKey('stake1u9ex0jtl4nv84rlzwuft5rczy2hgkjygewla04mgy7v2nccx4p4yr',signed));
console.log('PASS: local wallet signature verification, reproducible nonextractable key, encryption, tampering and account mismatch.');
